name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  OUTPUT_NAME: "__bin__/${{ github.repository }}"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.2'

      - name: Format code
        run: go fmt $(go list ./... | grep -v /vendor/)

      - name: Vet code
        run: go vet $(go list ./... | grep -v /vendor/)

      - name: Run tests
        run: |
          go test -race $(go list ./... | grep -v /vendor/)

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.2'
      - name: Build
        run: |
          mkdir -p ${{ env.OUTPUT_NAME }}
          go build -o ${{ env.OUTPUT_NAME }} ./...
